FinalExam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.login, name='login'),
    path('bad_login/', views.login, name='bad_login'),

    path('logout/', views.logout, name='logout'),

    path('signup/', views.signup, name='signup'),

    path('profile/', views.profile, name='profile'),

]

posts/urls.py
from django.urls import path
from . import views # class
from .views import * # function

app_name = 'posts'

urlpatterns = [
    path('index/',viewbase, name = 'index'),
    path('view_information/', viewinformation, name='view_information'),  # 추가
    path('view_algorithm/', viewalgorithm, name='view_algorithm'),
    path('view_data/', viewdata, name='view_data'),

    path('view_purchase/', viewpurhase, name='view_purchase'),

    path('view_parser/', viewparser, name='view_parser'),
    path('view_parser/<int:user_id>', cart_algorithm, name='cart_algorithm'),
    path('view_parser2/', viewparser2, name='view_parser2'),
    path('view_parser2/<int:user_id>', cart_algorithm2, name='cart_algorithm2'),
    path('view_parser3/', viewparser3, name='view_parser3'),
    path('view_parser3/<int:user_id>', cart_algorithm3, name='cart_algorithm3'),

    path('view_cart/', cart_view, name='view_cart'),
    path('cart_calculate/', cart_calculate, name='cart_calculate'),

    path('view_cart/delete/<int:id>/', views.delete, name='delete'),

    path('cart_pie/', views.view_piechart, name='cart_pie'),
]

templates/bad_login.html
{% extends "baseForBadLogin.html" %}

{% block main %}

존재하지 않는 회원입니다. 다시 로그인해주세요.
<br/>
<a href="{% url 'accounts:login' %}">다시 로그인하기</a>

{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script src="https://d3js.org/d3.v6.js"></script>
{#        <!-- Plugin for color scale -->#}
    <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>



    <title>Final Exam</title>

    <style>
     .my_dataviz {
      float:left;}
     .legend {
      display:inline-block; width:250px; height:250px; margin-left:10px;}
     .header_graph { margin-left:4%; }
     {#<!-- Tooltip style -->#}
     .tooltip {
      background-color: black;
      border: none;
      border-radius: 5px;
      padding: 15px;
      min-width: 400px;
      text-align: left;
      color: white;
        }

     .balance {
        font-weight: bold;
     }

    </style>

    </head>
    <body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

{#prediction | results(db) 헤더 탭 생성#}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="/index">Description </a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="/">Login <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/logout">logout</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/profile">profile update</a>
                </li>

                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <span class="badge bg-secondary">{{user.username}}</span>
                    {% else %}
                    <span class="badge bg-secondary">Do Login</span>
                    {% endif %}
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_information">Information</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_algorithm">Algorithm</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_data">Data</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_parser">Cart_algorithm</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_parser2">Cart_Information</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_parser3">Cart_Data</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/view_cart">Cart</a>
                </li>
               <li class="nav-item">
                    <a class="nav-link" href="/cart_pie">Visual_Cart</a>
                </li>

            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    </body>
</html>

templates/baseForBadLogin.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://d3js.org/d3.v4.js"></script>
{#        <!-- Plugin for color scale -->#}
    <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

        
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>#}
{##}
{#    <!-- A functional reactive model library. github.com/curran/model -->#}
{#    <script src="https://curran.github.io/model/cdn/model-v0.2.4.js"></script>#}

    <title>Iris prediction</title>

    <style>
     .my_dataviz {
      float:left;}
     .legend {
      display:inline-block; width:250px; height:250px; margin-left:10px;}
     .header_graph { margin-left:4%; }
     {#<!-- Tooltip style -->#}
     .tooltip {
      background-color: black;
      border: none;
      border-radius: 5px;
      padding: 15px;
      min-width: 400px;
      text-align: left;
      color: white;
        }

    </style>

    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

{#prediction | results(db) 헤더 탭 생성#}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="/">Click this button! <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <span class="badge bg-secondary">{{user.username}}</span>
                    {% else %}
                    <span class="badge bg-secondary">Do Login</span>
                    {% endif %}
                </li>

            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/cart_pie.html
{% extends 'base.html' %}
{% block main %}

<div class = 'header_graph'>
    <h3> Bar Chart By Cart(Genre)</h3>
</div>

<!-- Add 2 buttons -->
<button onclick="update(data1)">Genre Count(int)</button>
<button onclick="update(data2)">Avg Price($)</button>

<div class = "my_dataviz">
<div id="my_dataviz"></div>
</div>

<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

<script>
const data1 = [
   {group: "Data", value: {{data_count}}},
   {group: "Inform", value: {{inform_count}}},
   {group: "Algorithm", value: {{algorithm_count}}}
];

const data2 = [
   {group: "Data", value: {{data_avg.price__avg|floatformat:0}}},
   {group: "Inform", value: {{inform_avg.price__avg|floatformat:0}}},
   {group: "Algorithm", value: {{algorithm_avg.price__avg|floatformat:0}}},
];

// set the dimensions and margins of the graph
const margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
const svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

// Initialize the X axis
const x = d3.scaleBand()
  .range([ 0, width ])
  .padding(0.2);
const xAxis = svg.append("g")
  .attr("transform", `translate(0,${height})`)

// Initialize the Y axis
const y = d3.scaleLinear()
  .range([ height, 0]);
const yAxis = svg.append("g")
  .attr("class", "myYaxis")


// A function that create / update the plot for a given variable:
function update(data) {

  // Update the X axis
  x.domain(data.map(d => d.group))
  xAxis.call(d3.axisBottom(x))

  // Update the Y axis
  y.domain([0, d3.max(data, d => d.value) ]);
  yAxis.transition().duration(1000).call(d3.axisLeft(y));

  // Create the u variable
  var u = svg.selectAll("rect")
    .data(data)

  u
    .join("rect") // Add a new rect for each new elements
    .transition()
    .duration(1000)
      .attr("x", d => x(d.group))
      .attr("y", d => y(d.value))
      .attr("width", x.bandwidth())
      .attr("height", d => height - y(d.value))
      .attr("fill", "#69b3a2")
}

// Initialize the plot with the first dataset
update(data1)

</script>

{% endblock %}

templates/copy.html
{% extends 'base.html' %}
{% block main %}

<div id="my_dataviz"></div>


<!-- Add 2 buttons -->
<button onclick="update(data1)">Variable 1</button>
<button onclick="update(data2)">Variable 2</button>

<div id="my_dataviz2"></div>

<script>

// set the dimensions and margins of the graph
const width = 450,
    height = 450,
    margin = 40;

// The radius of the pieplot is half the width or half the height (smallest one). I subtract a bit of margin.
const radius = Math.min(width, height) / 2 - margin

// append the svg object to the div called 'my_dataviz'
const svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width)
    .attr("height", height)
  .append("g")
    .attr("transform", `translate(${width / 2}, ${height / 2})`);

// Create dummy data
const data = {Data: {{data_count}}, Information: {{inform_count}}, Algorithm:{{algorithm_count}}}

// set the color scale
const color = d3.scaleOrdinal()
  .range(d3.schemeSet2);

// Compute the position of each group on the pie:
const pie = d3.pie()
  .value(function(d) {return d[1]})
const data_ready = pie(Object.entries(data))
// Now I know that group A goes from 0 degrees to x degrees and so on.

// shape helper to build arcs:
const arcGenerator = d3.arc()
  .innerRadius(0)
  .outerRadius(radius)

// Build the pie chart: Basically, each part of the pie is a path that we build using the arc function.
svg
  .selectAll('mySlices')
  .data(data_ready)
  .join('path')
    .attr('d', arcGenerator)
    .attr('fill', function(d){ return(color(d.data[0])) })
    .attr("stroke", "black")
    .style("stroke-width", "2px")
    .style("opacity", 0.7)

// Now add the annotation. Use the centroid method to get the best coordinates
svg
  .selectAll('mySlices')
  .data(data_ready)
  .join('text')
  .text(function(d){ return "grp " + d.data[0]})
  .attr("transform", function(d) { return `translate(${arcGenerator.centroid(d)})`})
  .style("text-anchor", "middle")
  .style("font-size", 17)
</script>


<script>

// create 2 data_set
const data1 = [
   {group: "A", value: 4},
   {group: "B", value: 16},
   {group: "C", value: 8}
];

const data2 = [
   {group: "A", value: 7},
   {group: "B", value: 1},
   {group: "C", value: 20}
];

// set the dimensions and margins of the graph
const margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
const svg = d3.select("#my_dataviz2")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

// X axis
const x = d3.scaleBand()
  .range([ 0, width ])
  .domain(data1.map(d => d.group))
  .padding(0.2);
svg.append("g")
  .attr("transform", `translate(0,${height})`)
  .call(d3.axisBottom(x))

// Add Y axis
const y = d3.scaleLinear()
  .domain([0, 20])
  .range([ height, 0]);
svg.append("g")
  .attr("class", "myYaxis")
  .call(d3.axisLeft(y));

// A function that create / update the plot for a given variable:
function update(data) {

  var u = svg.selectAll("rect")
    .data(data)

  u
    .join("rect")
    .transition()
    .duration(1000)
      .attr("x", d => x(d.group))
      .attr("y", d => y(d.value))
      .attr("width", x.bandwidth())
      .attr("height", d => height - y(d.value))
      .attr("fill", "#69b3a2")
}

// Initialize the plot with the first dataset
update(data1)

</script>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block main %}
{% load static %}

<h3>Brief Description</h3>
<br><br>

1. Information, Algorithm, Data -> Using Datatable, Bootstrap
<br><br>

2. Cart_algorithm, Cart_Information, Cart_Data, Cart -> using Bootstrap
<br><br>
3. Sign up -> login -> add a book to Cart -> purchase -> profile balance
<br><br>
4. Two ways to get the api
        <br>
    <li>one is getting in the template by data table by ajax url</li>
    <img src="{% static 'image/getapi1.png' %}" alt = "iris image" width = "30%">
        <br>
    <li>the other one is getting in the views.py using 'requests' library</li>
    <img src="{% static 'image/getapi2.png' %}" alt = "iris image" width = "30%">


{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block main %}

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6">
                            {% load static %}
                            <img src="{% static 'image/user.jpg' %}" alt = "user image" width = "90%">
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">LOG IN</h1>
                                    </div>
                                    <form class="user" method="POST">
                                    {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="username" name="username" aria-describedby="emailHelp"
                                                placeholder="Enter Your ID...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="password" name="password" placeholder="Password">
                                        </div>

                                        <br/><br/><br/>
                                        <input type="submit" value="login!" class="btn btn-success btn-user btn-block">
                                        <hr>

                                        </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'accounts:signup' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->

{#prediction results pop screen 나타나는 창#}

{#The Modal plugin is a dialog box/popup window that is displayed on top of the current page#}

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5">
                {% load static %}
                <img src="{% static 'image/user.jpg' %}" alt = "user image" width = "90%">
                </div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                        </div>
                        <form action="" id="post-form" >
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control form-control-user" id="username"
                                    placeholder="Username">
                            </div>

                            <div class="form-group">
                                <input type="email" class="form-control form-control-user" id="emailaddress"
                                    placeholder="Email Address">
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="password" class="form-control form-control-user"
                                        id="password1" placeholder="Password">
                                </div>
                                <div class="col-sm-6">
                                    <input type="password" class="form-control form-control-user"
                                        id="password2" placeholder="Repeat Password">
                                </div>
                            </div>
                            <input type="submit" class="btn btn-primary btn-user btn-block"
                            placeholder="Register">

                            <hr>

                        </form>
                        <hr>

                        <div class="text-center">
                            <a class="small" href={% url 'accounts:login' %}>Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{#<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{##}
{#    <div class="modal-dialog" role="document">#}
{#        <div class="modal-content">#}
{#            <div class="modal-header">#}
{#                <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>#}
{#                <button type="button" class="close" data-dismiss="modal" aria-label="Close">#}
{#                    <span aria-hidden="true">&times;</span>#}
{#                </button>#}
{#            </div>#}
{##}
{#            <div class="modal-body">#}
{##}
{#                <h5>registeration success! </h5>#}
{#                <div>User Name <span id="un"></span></div>#}
{#            </div>#}
{#            <div class="modal-footer">#}
{#                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#                <a class="btn btn-primary" href={% url 'accounts:login' %} role="button">Log in</a>#}
{#            </div>#}
{##}
{#        </div>#}
{#    </div>#}
{#</div>#}

<script>

    $(document).on('submit', '#post-form',function(e){
        {# submit -> 연쇄 다음 이벤트 묵살 -> ajax 실행 #}
        e.preventDefault();
        $.ajax({
            type:'POST',
            {#app = predict, reference url namespace => account: signup #}
            url:'{% url "accounts:signup" %}',
            data:{
                username:$('#username').val(),
                email:$('#emailaddress').val(),
                password:$('#password1').val(),
                repeat:$('#password2').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },

            success:function(json) {
                {#form 보냄이 성공하면 적은 내용 사라짐#}
                document.forms["post-form"].reset();
                {#document.getElementById("un").innerHTML = json['username'];#}
                alert('Sign up Success!');

            },
            error : function(xhr,errmsg,err) {
                console.log(err);
            }
        });
    })

</script>



{% endblock %}

templates/view_parser.html
{% extends 'base.html' %}
{% block main %}

    <div class="container pt-5">
        <div class="row">

        <h1>Algorithm Books</h1>

            <table class="table">
                <thead>
                <tr>
               <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Subtitle</th>
                <th scope="col">Isbn13</th>
                <th scope="col">Price</th>
                <th scope="col">Url</th>
                </tr>
                </thead>
                <tbody>
                {% for data in api %}
                    <tr id = {{forloop.counter}}>
                    <td class="row-data">{{forloop.counter}}</td>
                    <td class="row-data">{{ data.title }}</td>
                    <td class="row-data">{{ data.subtitle }}</td>
                    <td class="row-data">{{ data.isbn13 }}</td>
                    <td class="row-data">{{ data.price }}</td>
                    <td class="row-data">{{ data.url }}</td>
                    <td class="row-data"> <input type="button" class="checkBtn" value="Click"/></td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>


<script>

    $(".checkBtn").click(function() {

        var str = ""
        var tdArr = new Array();    // 배열 선언
        var checkBtn = $(this);

        // checkBtn.parent() : checkBtn의 부모는 <td>이다.
        // checkBtn.parent().parent() : <td>의 부모이므로 <tr>이다.
        var tr = checkBtn.parent().parent();
        var td = tr.children();

        console.log("클릭한 Row의 모든 데이터 : "+tr.text());

        var id = td.eq(0).text();
        var title = td.eq(1).text();
        var subtitle = td.eq(2).text();
        var isbn13 = td.eq(3).text();
        var price = td.eq(4).text();
        var url = td.eq(5).text();

        $.ajax({
            type:'POST',
            {#app = predict, reference url namespace => submit_prediction #}

            url:'{% url "posts:cart_algorithm" cartuser.id %}',
            data:{
                id: id,
                title: title,
                subtitle: subtitle,
                isbn13: isbn13,
                price : price,
                url : url,

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },

            success:function(json) {
                alert("Data send Sucess");
            },
            error : function(xhr,errmsg,err) {
                console.log(error);
            }
        });
    })

</script>


{% endblock %} 

templates/view_parser2.html
{% extends 'base.html' %}
{% block main %}

    <div class="container pt-5">
        <div class="row">

        <h1>Information Books</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Subtitle</th>
                <th scope="col">Isbn13</th>
                <th scope="col">Price</th>
                <th scope="col">Url</th>
                </tr>
                </thead>
                <tbody>
                {% for data in api %}
                    <tr id = {{forloop.counter}}>
                    <td class="row-data">{{forloop.counter}}</td>
                    <td class="row-data">{{ data.title }}</td>
                    <td class="row-data">{{ data.subtitle }}</td>
                    <td class="row-data">{{ data.isbn13 }}</td>
                    <td class="row-data">{{ data.price }}</td>
                    <td class="row-data">{{ data.url }}</td>
                    <td class="row-data"> <input type="button" class="checkBtn" value="Click"/></td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>


<script>

    $(".checkBtn").click(function() {

        var str = ""
        var tdArr = new Array();    // 배열 선언
        var checkBtn = $(this);

        // checkBtn.parent() : checkBtn의 부모는 <td>이다.
        // checkBtn.parent().parent() : <td>의 부모이므로 <tr>이다.
        var tr = checkBtn.parent().parent();
        var td = tr.children();

        console.log("클릭한 Row의 모든 데이터 : "+tr.text());

        var id = td.eq(0).text();
        var title = td.eq(1).text();
        var subtitle = td.eq(2).text();
        var isbn13 = td.eq(3).text();
        var price = td.eq(4).text();
        var url = td.eq(5).text();

        $.ajax({
            type:'POST',
            {#app = predict, reference url namespace => submit_prediction #}

            url:'{% url "posts:cart_algorithm2" cartuser.id%}',
            data:{
                id: id,
                title: title,
                subtitle: subtitle,
                isbn13: isbn13,
                price : price,
                url : url,

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },

            success:function(json) {
                alert("Data send Sucess");
            },
            error : function(xhr,errmsg,err) {
                console.log(error);
            }
        });
    })

</script>


{% endblock %} 

templates/view_parser3.html
{% extends 'base.html' %}
{% block main %}

    <div class="container pt-5">
        <div class="row">

        <h1>Data Books</h1>

            <table class="table">
                <thead>
                <tr>
               <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Subtitle</th>
                <th scope="col">Isbn13</th>
                <th scope="col">Price</th>
                <th scope="col">Url</th>
                </tr>
                </thead>
                <tbody>
                {% for data in api %}
                    <tr id = {{forloop.counter}}>
                    <td class="row-data">{{forloop.counter}}</td>
                    <td class="row-data">{{ data.title }}</td>
                    <td class="row-data">{{ data.subtitle }}</td>
                    <td class="row-data">{{ data.isbn13 }}</td>
                    <td class="row-data">{{ data.price }}</td>
                    <td class="row-data">{{ data.url }}</td>
                    <td class="row-data"> <input type="button" class="checkBtn" value="Click"/></td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>


<script>

    $(".checkBtn").click(function() {

        var str = ""
        var tdArr = new Array();    // 배열 선언
        var checkBtn = $(this);

        // checkBtn.parent() : checkBtn의 부모는 <td>이다.
        // checkBtn.parent().parent() : <td>의 부모이므로 <tr>이다.
        var tr = checkBtn.parent().parent();
        var td = tr.children();

        console.log("클릭한 Row의 모든 데이터 : "+tr.text());

        var id = td.eq(0).text();
        var title = td.eq(1).text();
        var subtitle = td.eq(2).text();
        var isbn13 = td.eq(3).text();
        var price = td.eq(4).text();
        var url = td.eq(5).text();

        $.ajax({
            type:'POST',
            {#app = predict, reference url namespace => submit_prediction #}

            url:'{% url "posts:cart_algorithm3" cartuser.id %}',
            data:{
                id: id,
                title: title,
                subtitle: subtitle,
                isbn13: isbn13,
                price : price,
                url : url,

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },

            success:function(json) {
                alert("Data send Sucess");
            },
            error : function(xhr,errmsg,err) {
                console.log(error);
            }
        });
    })

</script>


{% endblock %} 